version: '3.7'

services: 
  app:
    container_name: app
    # build: .
    image: dycelastic_app:latest
    command: npm start
    working_dir: /usr/src/app
    env_file:
      - .env
    ports:
      - "8080:8080"
    links:
      - mongo
      - elasticsearch
    depends_on: 
      - mongo
      - elasticsearch
  mongo:
    container_name: mongo
    ports:
      - "27017:27017"
    image: mongo
    volumes:
      - mongodb_data:/data/db
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9300:9300"
      - "9200:9200"
    depends_on:
      - mongo
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.6.1
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    depends_on: 
      - "elasticsearch"

volumes:
  mongodb_data:
    driver: local
  es_data:
    driver: local
